# FPGA Offload Evaluation Config
name: eval_GPU_only

generator:
  max_tokens: 4096
  dtype: fp16
  max_gen_len: 64    # ← 추가
  # attn_impl: sdpa  # ← 이거 추가

harness:
  tasks:
    - hellaswag
    - piqa
    - task: nq_open
      num_fewshot: 5
  limit: 100

